{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGrammar.
--   Generated by the BNF converter.

module PrintGrammar where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsGrammar

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGrammar.Ident where
  prt _ (AbsGrammar.Ident i) = doc $ showString i

instance Print AbsGrammar.Program where
  prt i = \case
    AbsGrammar.Prog decls -> prPrec i 0 (concatD [prt 0 decls])

instance Print [AbsGrammar.Decl] where
  prt = prtList

instance Print AbsGrammar.Block where
  prt i = \case
    AbsGrammar.Blk decls stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 decls, prt 0 stmts, doc (showString "}")])

instance Print AbsGrammar.Decl where
  prt i = \case
    AbsGrammar.VarDecl type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ";")])
    AbsGrammar.FnDecl type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGrammar.Arg where
  prt i = \case
    AbsGrammar.ValArg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsGrammar.RefArg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&"), prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Arg] where
  prt = prtList

instance Print [AbsGrammar.Stmt] where
  prt = prtList

instance Print AbsGrammar.Stmt where
  prt i = \case
    AbsGrammar.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsGrammar.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsGrammar.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsGrammar.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsGrammar.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsGrammar.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsGrammar.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.Interrupt inter -> prPrec i 0 (concatD [prt 0 inter, doc (showString ";")])
    AbsGrammar.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    AbsGrammar.Print expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGrammar.Inter where
  prt i = \case
    AbsGrammar.Break -> prPrec i 0 (concatD [doc (showString "break")])
    AbsGrammar.Continue -> prPrec i 0 (concatD [doc (showString "continue")])

instance Print AbsGrammar.Expr where
  prt i = \case
    AbsGrammar.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsGrammar.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsGrammar.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsGrammar.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsGrammar.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsGrammar.EString str -> prPrec i 6 (concatD [prt 0 str])
    AbsGrammar.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsGrammar.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsGrammar.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsGrammar.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsGrammar.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsGrammar.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsGrammar.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Expr] where
  prt = prtList

instance Print AbsGrammar.AddOp where
  prt i = \case
    AbsGrammar.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsGrammar.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsGrammar.MulOp where
  prt i = \case
    AbsGrammar.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsGrammar.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsGrammar.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsGrammar.RelOp where
  prt i = \case
    AbsGrammar.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsGrammar.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsGrammar.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsGrammar.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsGrammar.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsGrammar.NE -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print AbsGrammar.Type where
  prt i = \case
    AbsGrammar.Int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsGrammar.Str -> prPrec i 0 (concatD [doc (showString "string")])
    AbsGrammar.Bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsGrammar.Void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsGrammar.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Type] where
  prt = prtList

